name: evira_e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  build_runner: ^2.7.0
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.5.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_gen_runner: ^5.11.0
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  get_it: ^8.2.0
  go_router: ^16.2.0
  go_transitions: ^0.8.2
  google_fonts: ^6.3.0
  injectable: ^2.5.1
  injectable_generator: ^2.8.1
  rename: ^3.1.0
  my_flutter_toolkit:
    git:
      url: https://github.com/AmrSalahDev/MyFlutterToolKit.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/core/gen/
  integrations:
    image: true
    flutter_svg: true
    rive: false
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/splash/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
